GRANT CONNECT, RESOURCE TO RESTAURANTMANAGER ;  
grant insert, select,update on restaurant to RESTAURANTMANAGER;
grant insert, select,update on branch_address to RESTAURANTMANAGER;
grant insert,select,update on menu to RESTAURANTMANAGER;
grant insert, select,update on items to RESTAURANTMANAGER;
grant select,update on orders to RESTAURANTMANAGER;
grant insert, select,update on restaurant_coupon_relation to RESTAURANTMANAGER;
grant select on payment_type to RESTAURANTMANAGER;
grant insert, select,update on DELIVERY_BOY to RESTAURANTMANAGER;
grant insert, select,update on coupons to RESTAURANTMANAGER;
grant select on restaurant_sequence to RESTAURANTMANAGER;
grant select on orders_seq to RESTAURANTMANAGER;
grant select on branch_id_seq to RESTAURANTMANAGER;
grant select on items_seq to RESTAURANTMANAGER;
grant select on coupons_seq to RESTAURANTMANAGER;
grant select on RESTAURANT_COUPON_RELATION_SEQUENCE to RESTAURANTMANAGER;
commit;

GRANT CONNECT, RESOURCE TO DELIVERY_BOY ; 
grant select,update,INSERT on delivery_boy to DELIVERY_BOY;
grant select on customer to DELIVERY_BOY;
grant select on ordered_items to DELIVERY_BOY;
grant select on branch_address to DELIVERY_BOY;
grant select on ordered_items to DELIVERY_BOY;
grant select,update on orders to DELIVERY_BOY;
grant select on restaurant to DELIVERY_BOY;
grant create view to DELIVERY_BOY;
grant select on delivery_boy_seq to DELIVERY_BOY;
commit;

GRANT CONNECT, RESOURCE TO CUSTOMER ;  
grant insert, select,update on orders to customer;
grant select,insert, update on customer to customer;
grant insert,select,update on ordered_items to customer;
grant insert,select,update on payment_type to customer;
grant select on branch_address to customer;
grant select on menu to customer;
grant select on items to customer;
grant select on delivery_boy to customer;
grant select on restaurant to customer;
grant select on customers_seq to customer;
grant select on orders_seq to customer;
grant select on ORDERED_ITEMS_SEQ  to customer;
GRANT select on payment_type_seq to customer;
grant select on delivery_boy to customer;
grant select on coupons to customer;
grant select on restaurant_coupon_relation to customer;
grant create view to customer;
commit;
